### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by Arubinu** [derricksmith/Nagios-Event-Handlers-for-GLPI#1]
Hello,

I have installed Nagios XI (4.4.7) and would like to link it to GLPI (10.0.2).
It seems to me that your project is compatible? But I don't know how to integrate it.

Can you complete the README file with more explanation on this please.

Thanks.

**Comment by xventil** [comment]
i´ve goi it looking to see if i could install, haven´t tryed it, but you can read the info here

https://derrick-smith.com/update-for-nagios-eventhandler-and-glpi-9-1-ticketing-integration/

**Comment by Arubinu** [comment]
Thank you, we'll take a look.
